// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDkErFV7ZFkZ9JeXR1K7JErje-ztXuvg',
    appId: '1:1030847637185:web:9d62ada469c96de012d640',
    messagingSenderId: '1030847637185',
    projectId: 'notification-6313b',
    authDomain: 'notification-6313b.firebaseapp.com',
    storageBucket: 'notification-6313b.appspot.com',
    measurementId: 'G-ER2LJKY3MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaU9AwAqJTWc_3njMJpMWtQ0aiWL7kLJ8',
    appId: '1:1030847637185:android:9c9d4fcf6feae07012d640',
    messagingSenderId: '1030847637185',
    projectId: 'notification-6313b',
    storageBucket: 'notification-6313b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqew_hqvRLNn6xSAp2Z1x-ED0NZBBSCdc',
    appId: '1:1030847637185:ios:0432970d756b197812d640',
    messagingSenderId: '1030847637185',
    projectId: 'notification-6313b',
    storageBucket: 'notification-6313b.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqew_hqvRLNn6xSAp2Z1x-ED0NZBBSCdc',
    appId: '1:1030847637185:ios:7d2c56e6b6b8088f12d640',
    messagingSenderId: '1030847637185',
    projectId: 'notification-6313b',
    storageBucket: 'notification-6313b.appspot.com',
    iosBundleId: 'com.example.notification.RunnerTests',
  );
}
